#!/bin/bash
if termux-dialog confirm -t "Convert to mp3?" | grep -q "yes";
then
    extra_options="-x --audio-format mp3"
else
    extra_options="--recode-video mp4"
fi
yt-dlp $extra_options --exec "termux-media-scan {}; termux-toast 'Finished download'" -o "~/storage/downloads/%(title)s.%(ext)s" $1
